// <auto-generated />
using System;
using EMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.Migrations
{
    [DbContext(typeof(DeptDbContext))]
    partial class DeptDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EMS.DAL.DeptMaster", b =>
                {
                    b.Property<int>("DeptCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptCode"), 1L, 1);

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptCode");

                    b.ToTable("DeptMaster");

                    b.HasData(
                        new
                        {
                            DeptCode = 1,
                            DeptName = "Information Technology"
                        },
                        new
                        {
                            DeptCode = 2,
                            DeptName = "Human Resources"
                        },
                        new
                        {
                            DeptCode = 3,
                            DeptName = "Finance"
                        },
                        new
                        {
                            DeptCode = 4,
                            DeptName = "Marketing"
                        },
                        new
                        {
                            DeptCode = 5,
                            DeptName = "Sales"
                        },
                        new
                        {
                            DeptCode = 6,
                            DeptName = "Customer Support"
                        },
                        new
                        {
                            DeptCode = 7,
                            DeptName = "Research and Development"
                        },
                        new
                        {
                            DeptCode = 8,
                            DeptName = "Supply Chain"
                        },
                        new
                        {
                            DeptCode = 9,
                            DeptName = "Legal"
                        },
                        new
                        {
                            DeptCode = 10,
                            DeptName = "Public Relations"
                        });
                });

            modelBuilder.Entity("EMS.DAL.EmpProfile", b =>
                {
                    b.Property<int>("EmpCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpCode"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeptCode")
                        .HasColumnType("int");

                    b.Property<int?>("DeptMasterDeptCode")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpCode");

                    b.HasIndex("DeptMasterDeptCode");

                    b.ToTable("EmpProfile");

                    b.HasData(
                        new
                        {
                            EmpCode = 1,
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptCode = 1,
                            Email = "john.doe@example.com",
                            EmpName = "John Doe"
                        },
                        new
                        {
                            EmpCode = 2,
                            DateOfBirth = new DateTime(1991, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptCode = 2,
                            Email = "jane.smith@example.com",
                            EmpName = "Jane Smith"
                        },
                        new
                        {
                            EmpCode = 3,
                            DateOfBirth = new DateTime(1992, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptCode = 3,
                            Email = "william.johnson@example.com",
                            EmpName = "William Johnson"
                        },
                        new
                        {
                            EmpCode = 4,
                            DateOfBirth = new DateTime(1993, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptCode = 4,
                            Email = "patricia.williams@example.com",
                            EmpName = "Patricia Williams"
                        },
                        new
                        {
                            EmpCode = 5,
                            DateOfBirth = new DateTime(1994, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptCode = 5,
                            Email = "michael.brown@example.com",
                            EmpName = "Michael Brown"
                        },
                        new
                        {
                            EmpCode = 6,
                            DateOfBirth = new DateTime(1995, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptCode = 6,
                            Email = "linda.davis@example.com",
                            EmpName = "Linda Davis"
                        },
                        new
                        {
                            EmpCode = 7,
                            DateOfBirth = new DateTime(1996, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptCode = 7,
                            Email = "robert.miller@example.com",
                            EmpName = "Robert Miller"
                        },
                        new
                        {
                            EmpCode = 8,
                            DateOfBirth = new DateTime(1997, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptCode = 8,
                            Email = "elizabeth.wilson@example.com",
                            EmpName = "Elizabeth Wilson"
                        },
                        new
                        {
                            EmpCode = 9,
                            DateOfBirth = new DateTime(1998, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptCode = 9,
                            Email = "james.moore@example.com",
                            EmpName = "James Moore"
                        },
                        new
                        {
                            EmpCode = 10,
                            DateOfBirth = new DateTime(1999, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeptCode = 10,
                            Email = "barbara.taylor@example.com",
                            EmpName = "Barbara Taylor"
                        });
                });

            modelBuilder.Entity("EMS.DAL.EmpProfile", b =>
                {
                    b.HasOne("EMS.DAL.DeptMaster", "DeptMaster")
                        .WithMany("EmpProfiles")
                        .HasForeignKey("DeptMasterDeptCode");

                    b.Navigation("DeptMaster");
                });

            modelBuilder.Entity("EMS.DAL.DeptMaster", b =>
                {
                    b.Navigation("EmpProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
